hsmt/urls.py
from django.urls import path
from . import api_views, views

# just for debug
from django.conf import settings
from django.conf.urls.static import static
#--------------------------#

urlpatterns = [
    # Views
    path('', views.target_list_view, name='index'),
    path('hsmt/list/', views.hsmt_list_view, name='hsmt-list'),
    path('hsmt/edit-detail/', views.hsmt_edit_detail, name='hsmt-detail'),
    path('target/list/', views.target_list_view, name='target-list'),

    # XFileType API
    # LCRUD - list, create, retrieve, update, destroy
    path('api/hsmt-type/', api_views.XFileTypeListCreateView.as_view(), name='api_xfile_type_L'),
    path('api/hsmt-type/<int:pk>/', api_views.XFileTypeRetrieveUpdateDestroyView.as_view(), name='api_xfile_type_RUD'),
    # Target API
    path('api/target/', api_views.TargetListCreateView.as_view(), name='api_target_LC'),
    path('api/target/<int:pk>/', api_views.TargetRetrieveUpdateDestroy.as_view(), name='api_target_RUD'),
    # XFile API
    path('api/hsmt/', api_views.XFileListView.as_view(), name='api_xfile_L'),
    path('api/hsmt/create/', api_views.XFileCreateView.as_view(), name='api_xfile_C'),
    path('api/hsmt/<int:pk>/perm/', api_views.XFilePermView.as_view(), name='api_xfile_perm'), # quyền của user với xfile
    path('api/hsmt/<int:pk>/perm-update/', api_views.XFilePermUpdateView.as_view(), name='api_xfile_U_perm'), # sửa đổi danh sách editors, checkers, approvers
    path('api/hsmt/<int:pk>/general/', api_views.XFileRetrieveDestroyView.as_view(), name='api_xfile_RD_general'),
    path('api/hsmt/<int:pk>/general-update/', api_views.XFileGeneralUpdateView.as_view(), name='api_xfile_U_general'),
    path('api/hsmt/<int:pk>/content/', api_views.XFileContentRetrieveUpdateView.as_view(), name='api_xfile_RU_content'),
    #-------------------------xfile comments---------------------------------------------------------#
    path('api/hsmt/<int:pk>/comments/', api_views.XFileCommentListView.as_view(), name='api_xfile_L_comment'),
    path('api/hsmt/<int:pk>/comments/create/', api_views.XFileCommentCreateView.as_view(), name='api_xfile_C_comment'),
    path('api/hsmt/<int:pk>/comments/<int:comment_id>/', api_views.XFileCommentRetrieveUpdateDestroyView.as_view(), name='api_xfile_RUD_comment'),
    #-------------------------attack logs---------------------------------------------------------#
    path('api/hsmt/<int:pk>/attacklogs/', api_views.AttackLogListView.as_view(), name='api_xfile_L_attacklog'),
    path('api/hsmt/<int:pk>/attacklogs/create/', api_views.AttackLogCreateView.as_view(), name='api_xfile_C_attacklog'),
    path('api/hsmt/<int:pk>/attacklogs/<int:attacklog_id>/', api_views.AttackLogRetrieveUpdateDeleteView.as_view(), name='api_xfile_RUD_attacklog'),
    #-------------------------xfile changes---------------------------------------------------------#
    path('api/hsmt/<int:pk>/changes/', api_views.XFileChangeListView.as_view(), name='api_xfile_L_change'),
    path('api/hsmt/<int:pk>/changes/<int:version>/', api_views.XFileChangeRetrieveUpdateView.as_view(), name='api_xfile_RU_change'),
    #-------------------------xfile functions---------------------------------------------------------#
    path('api/hsmt/<int:pk>/create-change/',api_views.XFileChangeCreateView.as_view(), name='hsmt-create-change'),
    path('api/hsmt/<int:pk>/cancel-change/',api_views.XFileChangeCancelView.as_view(), name='hsmt-cancel-change'),
    path('api/hsmt/<int:pk>/submit/',api_views.XFileChangeSubmitView.as_view(), name='hsmt-submit'),
    path('api/hsmt/<int:pk>/check/',api_views.XFileChangeCheckView.as_view(), name='hsmt-check'),
    path('api/hsmt/<int:pk>/reject-check/',api_views.XFileChangeRejectCheckView.as_view(), name='hsmt-reject-check'),
    path('api/hsmt/<int:pk>/approve/',api_views.XFileChangeApproveView.as_view(), name='hsmt-approve'),
    path('api/hsmt/<int:pk>/reject-approve/',api_views.XFileChangeRejectApproveView.as_view(), name='hsmt-reject-approve'),
    
    # ------------------------------------------------------------------------------#
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

test_hsmt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('hsmt.urls')),
    path('', include('notifications.urls')),
    path('', include('todolist.urls')),
]

hsmt/models.py
import json
from copy import deepcopy
from datetime import datetime, date
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import gettext_lazy as _
from django_fsm import transition, GET_STATE, FSMIntegerField
from users.models import User, Department

# Choices
class STATUS(models.IntegerChoices):
    '''
    Những trạng thái của XFile
    '''
    INIT = 0, _('khởi tạo')
    EDITING = 1, _('đang sửa đổi')
    CHECKING = 2, _('đang kiểm định')
    APPROVING = 3, _('đang phê duyệt')
    DONE = 4, _('đã hoàn thiện')
    
class TARGET_TYPES(models.IntegerChoices):
    '''
    Những loại của Target
    '''
    DIRECTION = 1, _('hướng'),
    GROUP = 2, _('nhóm mục tiêu'),
    AREA = 3, _('địa bàn'),

# Models here.
class XFileType(models.Model):
    '''
    Biểu diễn loại (type) hồ sơ
    '''
    name = models.CharField(max_length=120)
    example_content = models.TextField() # nội dung mẫu

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = self.name.lower()
        return super().save(*args, **kwargs)

class Target(models.Model):
    '''
    Biểu diễn hướng - nhóm - địa bàn
    '''
    name = models.CharField(max_length=120)
    description = models.TextField(blank=True)
    type = models.PositiveIntegerField(choices=TARGET_TYPES.choices)

    def __str__(self):
        return f'{self.get_type_display()} {self.name}'

class XFile(models.Model):
    '''
    Biểu diễn XFile
    '''
    # Nội dung bìa
    code = models.CharField(max_length=120, unique=True)
    description = models.TextField(blank=True)
    status = FSMIntegerField(
        choices = STATUS.choices,
        default = STATUS.INIT,
        protected = True
    )
    date_created = models.DateField(default=date.today)
    type = models.ForeignKey(XFileType, on_delete=models.CASCADE)
    targets = models.ManyToManyField(Target)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    
    # Nội dung ẩn
    content = models.TextField(blank=True)
    version = models.PositiveIntegerField(default=0)
    
    # Phân quyền
    creator = models.ForeignKey(User, related_name='xfiles_created', on_delete=models.PROTECT)
    editors = models.ManyToManyField(User, related_name='xfiles_can_edit')
    checkers = models.ManyToManyField(User, related_name='xfiles_can_check')
    approvers = models.ManyToManyField(User, related_name='xfiles_can_approve')
    comments = GenericRelation('Comment')
    
    def __str__(self):
        return f'hồ sơ {self.code}'

    # Chức năng riêng
    def get_xfile_content(self):
        '''
        Trả lại JSON dict thể hiện tất cả nội dung của XFile theo cấu trúc
        '''
        content = {}
        general_content = ['code', 'description', 'targets', 'department', 'attack_logs', 'editors', 'checkers', 'approvers']
        for field in general_content:
            record = {}
            value = getattr(self, field)
            if type(value) == str:
                record['type'] = 'string'
            elif field == 'targets':
                record['type'] = 'target'
                value = list(value.all())
            elif field == 'department':
                record['type'] = 'department'
            elif field in ['editors', 'checkers', 'approvers']:
                record['type'] = 'user'
                value = list(value.all())
            elif field == 'attack_logs':
                record['type'] = 'attacklog'
                value = list(value.all())
            record['value'] = value
            content[field] = record
        
        secret_content = json.loads(self.content)
        for field, record in secret_content.items():
            if record.get('type') == 'datetime':
                try:
                    record['value'] = datetime.strptime(record['value'], '%b %d %Y').date()
                except:
                    record['value'] = date(1,1,1)

        return content | secret_content

    def get_xfile_by_version(self, version):
        '''
        Áp dụng thay đổi lần lượt, trả lại phiên bản XFile object có version tương ứng
        '''
        xfile = deepcopy(self)
        cur_version = xfile.version
        # Nếu đúng version trả về luôn
        if cur_version == version:
            return xfile
        # Nếu khác version thì áp dụng phiên bản mới (forward) 
        # hoặc lùi lại phiên bản cũ (backward)
        if cur_version < version:
            forward = 1
        else: forward = -1
        for v in range(cur_version, version, forward):
            try:
                if forward == 1:
                    change = xfile.changes.get(version = v+1)
                    change.apply_to_xfile()
                else:
                    change = xfile.changes.get(version = v)
                    change.apply_to_xfile(backward=True)
            except:
                # Nếu không tồn tại phiên bản tương ứng -> None
                return None
        return xfile

    # Permisions control
    def can_view(self, user=None):
        if not user:
            return False
        if user in list(self.editors.all()):
            return True
        if user in list(self.checkers.all()): # and self.status not in [STATUS.INIT, STATUS.EDITING]:
            return True
        if user in list(self.approvers.all()):
            return True
        if user.department.alias == 'giamdoc':
            return True
        return False

    def can_edit(self, user=None):
        if not user:
            return False
        if user in list(self.editors.all()):
            return True
        return False

    def can_check(self, user=None):
        if not user:
            return False
        if user in list(self.checkers.all()):
            return True
        return False

    def can_approve(self, user=None):
        if not user:
            return False
        if user in list(self.approvers.all()):
            return True
        return False

    # Finite-state machine
    @transition(
        field=status,
        source= STATUS.EDITING,
        target= STATUS.CHECKING,
        permission=can_edit
    )
    def submit_change(self, by=None):
        '''
        - Change status to CHECKING
        - Save XFileChange.editor, XFileChange.date_submited
        '''
        xfilechange = self.changes.get(version = self.version)
        xfilechange.editor = by
        xfilechange.date_submited = date.today()
        xfilechange.save()

    @transition(
        field=status,
        source= STATUS.CHECKING,
        target= STATUS.APPROVING,
        permission=can_check
    )
    def check_change(self, by=None):
        '''
        - Change status to APPROVING
        - Save XFileChange.checker, XFileChange.date_checked
        '''
        xfilechange = self.changes.get(version = self.version)
        xfilechange.checker = by
        xfilechange.date_checked = date.today()
        xfilechange.save()

    @transition(
        field=status,
        source= STATUS.APPROVING,
        target= STATUS.DONE,
        permission=can_approve
    )
    def approve_change(self, by=None):
        '''
        - Change status to DONE
        - Save XFileChange.approver, XFileChange.date_approved
        '''
        xfilechange = self.changes.get(version = self.version)
        xfilechange.approver = by
        xfilechange.date_approved = date.today()
        xfilechange.save()

    @transition(
        field=status,
        source= [STATUS.INIT, STATUS.DONE],
        target= STATUS.EDITING,
        permission=can_edit
    )
    def create_change(self, change_name, by=None):
        '''
        - Change status to EDITING
        - Create new XFileChange, XFileChange.date_created,
        - Apply change to XFile
        '''
        new_change = self.changes.create(name = change_name)
        new_change.date_created = date.today()
        new_change.editor = by
        new_change.apply_to_xfile()
        new_change.save()

    @transition(
        field=status,
        source= STATUS.CHECKING,
        target= STATUS.EDITING,
        permission=can_check
    )
    def reject_check(self, by=None):
        '''
        Change status to EDITING
        '''
        pass

    @transition(
        field=status,
        source= STATUS.APPROVING,
        target= STATUS.CHECKING,
        permission=can_approve
    )
    def reject_approve(self, by=None):
        '''
        Change status to CHECKING
        '''
        pass

    @transition(
        field=status,
        source= STATUS.EDITING,
        target= GET_STATE(
            lambda self, **kwargs: STATUS.INIT if self.version == 0 else STATUS.DONE,
            states=[STATUS.DONE, STATUS.INIT]
        ),
        permission=can_edit
    )
    def cancel_change(self, by=None):
        '''
        - Change status to INIT or DONE according to (xfile.version = 0 or not)
        - Reverse change from XFile
        - Delete XFileChange
        '''
        xfilechange = self.changes.get(version = self.version)
        xfilechange.apply_to_xfile(backward = True)
        xfilechange.delete()

class XFileChange(models.Model):
    '''
    Biểu diễn thay đổi của XFile
    '''
    # Nội dung được tự động tạo
    version = models.PositiveIntegerField(default=None, null=True, blank=True)
    date_created = models.DateField(default=date.today)
    date_edited = models.DateField(blank=True, null=True)
    date_submited = models.DateField(blank=True, null=True)
    date_checked = models.DateField(blank=True, null=True)
    date_approved = models.DateField(blank=True, null=True)
    editor = models.ForeignKey(User, on_delete=models.PROTECT, related_name='changes_edited', null=True)
    checker = models.ForeignKey(User, on_delete=models.PROTECT, related_name='changes_checked', null=True)

hsmt/forms.py
from django import forms
from .models import XFile

class XFileCreateForm(forms.ModelForm):
    
    class Meta:
        model = XFile
        fields = ['code', 'description', 'type', 'editors', 'checkers', 'approvers', 'targets']

class XFileUpdateForm(forms.ModelForm):

    class Meta:
        model = XFile
        fields = ['code', 'description', 'targets', 'content', 'department']

hsmt/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator

from django.http import HttpResponseForbidden

from hsmt.models import *
from notifications.utils import notify, VERB

# XFile views

@login_required
def hsmt_list_view(request):
    title='Danh sách HSMT'
    context={
        'breadcrumb':title,
        'h1header':title,
        'xfile_types': XFileType.objects.all(),
        'users': User.objects.filter(department=request.user.department).select_related('position'),
        'targets': Target.objects.all()
    }
    return render(request, 'hsmt/hsmt-list.html',context)

@login_required
def target_list_view(request):
    title='Danh sách Hướng - Nhóm - Địa Bàn'
    context={
        'breadcrumb':title,
        'h1header':title,
        'targets': TARGET_TYPES.choices
    }
    return render(request, 'hsmt/target-type-list.html',context)

@login_required
def hsmt_edit_detail(request):
    xfileId = request.GET.get('id',-1)
    title='Chỉnh sửa HSMT'
    context={ }
    # xfile_type='1'
    originalXfileId=xfileId
    xfile = get_object_or_404(XFile, id=xfileId)
    if not xfile.can_view(request.user):
        return HttpResponseForbidden()

    title += ' - '+ xfile.type.name
        
    context['xfile_type'] = str(xfile.type.id)
    context['xfileId']=xfileId
    context['xfile_status']=xfile.get_status_display()
    context['originalXfileId']=originalXfileId
    context['breadcrumb']=title
    context['h1header']=title
    context['user_layout']=request.user
    return render(request, 'hsmt/hsmt-detail.html',context)

hsmt/templates/hsmt/XFILE-ORG.html
<div class="card card-default">
    <div class="card-header" data-card-widget="collapse" >
        <h3 class="card-title">THÔNG TIN LÝ LỊCH</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" >
                <i class="fas fa-minus"></i>
            </button>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label>1. Tên gọi và các tên gọi khác</label>
                    <textarea type="text" class="form-control" id="hoVaTen"></textarea>
                    <div class="feedback" style="color: red;" id="hoVaTen-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            
        </div>
        <div class="row">
            <label>2. Thời gian thành lập</label>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label>2a. Thời gian tổ chức thành lập</label>
                    <div class="input-group date" id="dtp2" data-target-input="nearest">
                        <input type="text" class="form-control datetimepicker-input" data-target="#dtp2" id="thoiGianThanhLap">
                        <div class="input-group-append" data-target="#dtp2" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                <!-- /.form-group -->
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>2b. Thời gian xuất hiện trên KGM</label>
                    <div class="input-group date" id="dtp3" data-target-input="nearest">
                        <textarea type="text" class="form-control datetimepicker-input" data-target="#dtp3" id="thoiGianXuatHien"></textarea>
                        <div class="input-group-append" data-target="#dtp3" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                </div>
                <!-- /.form-group -->
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label>3. Địa chỉ và số điện thoại</label>
                    <textarea type="text" class="form-control" id="diaChivaSDT"></textarea>
                    <div class="feedback" style="color: red;" id="diaChivaSDT-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            <!-- /.col -->
            <div class="col-md-8">
                <div class="form-group">
                    <label>4. Mục tiêu trên mạng</label>
                    <textarea type="text" class="form-control" id="mucTieuTrenMang"></textarea>
                    <div class="feedback" style="color: red;" id="mucTieuTrenMang-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
        </div>
        <!-- /.row -->
        <div class="row">
            <label>5. Tổ chức</label>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label>5a. Cơ cấu tổ chức, các bộ phận, chi nhánh</label>
                    <textarea type="text" class="form-control" id="coCauToChuc"></textarea>
                    <div class="feedback" style="color: red;" id="coCauToChuc-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>5b. Lãnh đạo/quản trị, thành viên chủ chốt</label>
                    <textarea type="text" class="form-control" id="lanhDaoQuanTri"></textarea>
                    <div class="feedback" style="color: red;" id="lanhDaoQuanTri-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>5c. Số lượng thành viên</label>
                    <textarea type="text" class="form-control" id="soLuongThanhVien"></textarea>
                    <div class="feedback" style="color: red;" id="soLuongThanhVien-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            <!-- /.col -->
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label>5d. Cách thức, quy trình, quy định tuyển chọn thành viên</label>
                    <textarea type="text" class="form-control" id="quyTrinhTuyenChon"></textarea>
                    <div class="feedback" style="color: red;" id="quyTrinhTuyenChon-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>5e. Địa bàn hoạt động</label>
                    <textarea type="text" class="form-control" id="diaBanHoatDong"></textarea>
                    <div class="feedback" style="color: red;" id="diaBanHoatDong-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>6. Tôn chỉ, mục đích</label>
                    <textarea type="text" class="form-control" id="tonChiMucDich"></textarea>
                    <div class="feedback" style="color: red;" id="tonChiMucDich-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            
            <!-- /.col -->
        </div>
        <!-- /.row -->
        <div class="row">
            <label>7. Quá trình hoạt động</label>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>7a. Đặc điểm, quy luật, nội dung, thủ đoạn, các hoạt động chống phá</label>
                    <textarea type="text" class="form-control" id="quaTrinhHinhThanh"></textarea>
                    <div class="feedback" style="color: red;" id="quaTrinhHinhThanh-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>7b. Tần suất, lưu lượng đăng tải, mức độ quan tâm</label>
                    <textarea type="text" class="form-control" id="tanSuatHoatDong"></textarea>
                    <div class="feedback" style="color: red;" id="tanSuatHoatDong-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label>7c. Tổ chức/cá nhân chỉ đạo, tài trợ</label>
                    <textarea type="text" class="form-control" id="toChucTaiTro"></textarea>
                    <div class="feedback" style="color: red;" id="toChucTaiTro-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label>7d. Các tổ chức, mục tiêu có liên quan</label>
                    <textarea type="text" class="form-control" id="toChucLienQuan"></textarea>
                    <div class="feedback" style="color: red;" id="toChucLienQuan-feedback"></div>
                </div>
                <!-- /.form-group -->
            </div>
        </div>
        <!-- /.row -->
        
    </div>
    <!-- /.card-body -->
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">THÔNG TIN KỸ THUẬT</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>1. Địa chỉ máy chủ, nhà cung cấp dịch vụ</label>
                            <textarea type="text" class="form-control" id="diaChiMayChu"></textarea>
                            <div class="feedback" style="color: red;" id="diaChiMayChu-feedback"></div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>2. Quản trị: tổ chức/cá nhân đăng ký, quản trị, thuê</label>
                            <textarea type="text" class="form-control" id="quanTri"></textarea>

                            <div class="feedback" style="color: red;" id="quanTri-feedback"></div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>3. Đặc điểm sử dụng phần mềm, kỹ thuật thể hiện</label>
                            <textarea type="text" class="form-control" id="dacDiemSuDung"></textarea>
                            <div class="feedback" style="color: red;" id="dacDiemSuDung-feedback"></div>
                        </div>
                        <!-- /.form-group -->
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </div>
        <!-- /.card -->
    </div>
<div class="col-lg-6">
    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">ĐÁNH GIÁ</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Về giá trị TB, tin tức</label>
                        <textarea type="text" class="form-control" id="giaTriTB"></textarea>
                        <div class="feedback" style="color: red;" id="giaTriTB-feedback"></div>
                    </div>
                    <!-- /.form-group -->
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Khả năng tiếp cận bằng kỹ thuật</label>
                        <textarea type="text" class="form-control" id="khaNangTiepCanKT"></textarea>
                        <div class="feedback" style="color: red;" id="khaNangTiepCanKT-feedback"></div>
                    </div>
                    <!-- /.form-group -->
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label>Khả năng tiếp cận bằng ĐB</label>
                        <textarea type="text" class="form-control" id="khaNangTiepCanDB"></textarea>
                        <div class="feedback" style="color: red;" id="khaNangTiepCanDB-feedback"></div>
                    </div>
                    <!-- /.form-group -->
                </div>
            </div>
            <!-- /.row -->
        </div>
      
    </div>
    <!-- /.card -->
    </div>
</div>

hsmt/templates/hsmt/list.html
{% extends 'hsmt/base.html' %}

{% block data %}
    <div class="row">
        <div class="col-lg-12 mb-4">
            <a href="{% url 'hsmt-create' %}" class="btn float-right text-primary font-weight-bold">
                Tạo mới
            </a>
        </div>
    </div>
    
    {% for xfile in xfile_list %}
        <!-- Content Row -->
        <div class="row">
            <!-- Content Column -->
            <div class="col-lg-12 mb-4">
                <!-- Project Card Example -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <a class="btn m-0 p-0 font-weight-bold text-primary" href="{% url 'hsmt-detail' xfile.id %}">
                            {{ xfile }} (ver {{xfile.version}})
                        </a>
                        <span class="float-right text-primary font-weight-bold"> Trạng thái: {{ xfile.get_status_display }}</span>
                    </div>
                    <div class="card-body">
                        <h4 class="small font-weight-bold">
                            Loại hồ sơ
                            <span class="float-right">{{xfile.type}}</span>
                        </h4>
                        <h4 class="small font-weight-bold">
                            Mã số
                            <span class="float-right">{{xfile.code}}</span>
                        </h4>
                        <h4 class="small font-weight-bold">
                            Ngày tạo
                            <span class="float-right">{{xfile.date_created}}</span>
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock data %}

hsmt/templates/hsmt/type_list.html
{% extends 'hsmt/base.html' %}

{% block data %}
    <!-- Content Row -->
    <div class="row">
        <!-- Content Column -->
        <div class="col-lg-12 mb-4">
            <!-- Project Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">
                        Danh sách các loại hồ sơ
                        <a href="{% url 'hsmt-type-create' %}" class="float-right">
                            Tạo mới
                        </a>
                    </h6>
                </div>
                <div class="card-body">
                    {% for xfiletype in xfiletype_list %}
                        <h4 class="small font-weight-bold">
                            {{xfiletype.name}} 
                            <a href="{% url 'hsmt-type-detail' xfiletype.id %}" class="float-right">
                                Chi tiết
                            </a>
                        </h4>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock data %}