hsmt/urls.py
from django.urls import path
from . import api_views, views

# just for debug
from django.conf import settings
from django.conf.urls.static import static
#--------------------------#

urlpatterns = [
    # Views
    path('', views.target_list_view, name='index'),
    path('hsmt/list/', views.hsmt_list_view, name='hsmt-list'),
    path('hsmt/edit-detail/', views.hsmt_edit_detail, name='hsmt-detail'),
    path('target/list/', views.target_list_view, name='target-list'),

    # XFileType API
    # LCRUD - list, create, retrieve, update, destroy
    path('api/hsmt-type/', api_views.XFileTypeListCreateView.as_view(), name='api_xfile_type_L'),
    path('api/hsmt-type/<int:pk>/', api_views.XFileTypeRetrieveUpdateDestroyView.as_view(), name='api_xfile_type_RUD'),
    # Target API
    path('api/target/', api_views.TargetListCreateView.as_view(), name='api_target_LC'),
    path('api/target/<int:pk>/', api_views.TargetRetrieveUpdateDestroy.as_view(), name='api_target_RUD'),
    # XFile API
    path('api/hsmt/', api_views.XFileListView.as_view(), name='api_xfile_L'),
    path('api/hsmt/create/', api_views.XFileCreateView.as_view(), name='api_xfile_C'),
    path('api/hsmt/<int:pk>/perm/', api_views.XFilePermView.as_view(), name='api_xfile_perm'), # quyền của user với xfile
    path('api/hsmt/<int:pk>/perm-update/', api_views.XFilePermUpdateView.as_view(), name='api_xfile_U_perm'), # sửa đổi danh sách editors, checkers, approvers
    path('api/hsmt/<int:pk>/general/', api_views.XFileRetrieveDestroyView.as_view(), name='api_xfile_RD_general'),
    path('api/hsmt/<int:pk>/general-update/', api_views.XFileGeneralUpdateView.as_view(), name='api_xfile_U_general'),
    path('api/hsmt/<int:pk>/content/', api_views.XFileContentRetrieveUpdateView.as_view(), name='api_xfile_RU_content'),
    #-------------------------xfile comments---------------------------------------------------------#
    path('api/hsmt/<int:pk>/comments/', api_views.XFileCommentListView.as_view(), name='api_xfile_L_comment'),
    path('api/hsmt/<int:pk>/comments/create/', api_views.XFileCommentCreateView.as_view(), name='api_xfile_C_comment'),
    path('api/hsmt/<int:pk>/comments/<int:comment_id>/', api_views.XFileCommentRetrieveUpdateDestroyView.as_view(), name='api_xfile_RUD_comment'),
    #-------------------------attack logs---------------------------------------------------------#
    path('api/hsmt/<int:pk>/attacklogs/', api_views.AttackLogListView.as_view(), name='api_xfile_L_attacklog'),
    path('api/hsmt/<int:pk>/attacklogs/create/', api_views.AttackLogCreateView.as_view(), name='api_xfile_C_attacklog'),
    path('api/hsmt/<int:pk>/attacklogs/<int:attacklog_id>/', api_views.AttackLogRetrieveUpdateDeleteView.as_view(), name='api_xfile_RUD_attacklog'),
    #-------------------------xfile changes---------------------------------------------------------#
    path('api/hsmt/<int:pk>/changes/', api_views.XFileChangeListView.as_view(), name='api_xfile_L_change'),
    path('api/hsmt/<int:pk>/changes/<int:version>/', api_views.XFileChangeRetrieveUpdateView.as_view(), name='api_xfile_RU_change'),
    #-------------------------xfile functions---------------------------------------------------------#
    path('api/hsmt/<int:pk>/create-change/',api_views.XFileChangeCreateView.as_view(), name='hsmt-create-change'),
    path('api/hsmt/<int:pk>/cancel-change/',api_views.XFileChangeCancelView.as_view(), name='hsmt-cancel-change'),
    path('api/hsmt/<int:pk>/submit/',api_views.XFileChangeSubmitView.as_view(), name='hsmt-submit'),
    path('api/hsmt/<int:pk>/check/',api_views.XFileChangeCheckView.as_view(), name='hsmt-check'),
    path('api/hsmt/<int:pk>/reject-check/',api_views.XFileChangeRejectCheckView.as_view(), name='hsmt-reject-check'),
    path('api/hsmt/<int:pk>/approve/',api_views.XFileChangeApproveView.as_view(), name='hsmt-approve'),
    path('api/hsmt/<int:pk>/reject-approve/',api_views.XFileChangeRejectApproveView.as_view(), name='hsmt-reject-approve'),
    
    # ------------------------------------------------------------------------------#
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

test_hsmt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('hsmt.urls')),
    path('', include('notifications.urls')),
    path('', include('todolist.urls')),
]

users/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from . import views, api_views

# just for debug
from django.conf import settings
from django.conf.urls.static import static
#--------------------------#

urlpatterns = [
    # Views
    path('login/',views.login_view, name='user-login'),
    path('logout/',views.logout_view, name='user-logout'),
    path('register/',views.register_view, name='user-register'),
    path('success/',views.success_view, name='user-success'),
    path('user/list/',views.user_list_view, name='user-list'),
    path('profile/', views.profile_view, name='user-profile'),
    path('group/list/', views.group_list_view, name='group-list'),
    
    # APIs
    path('register-api/', views.register_api, name='user-register-api'),
    path('get-users/', views.get_users, name='get-users'),
    path('activate-user/', views.activate_user, name='activate-user'),
    path('delete-user/', views.delete_user, name='delete-user'),
    path('edit-user-info/', views.edit_user_info, name='edit-user-info'),
    path('change-password/', views.change_password, name='change-password'),

    # REST APIs
    path('api/department/', api_views.DepartmentListView.as_view(), name='api_department_list'),
    path('api/department/change-pwd/', api_views.department_change_pwd, name='api_department_change_pwd'),
    path('api/department/login/', api_views.department_login, name='api_department_login'),

    path('api/position/', api_views.PositionListView.as_view(), name='api_list_position'),

    path('api/login/', TokenObtainPairView.as_view(), name='api_user_login'),
    path('api/login/refresh/', TokenRefreshView.as_view(), name='api_user_refresh'),
    path('api/user/', api_views.UserListView.as_view(), name='api_user_list'),
    path('api/user/me/', api_views.UserMeView.as_view(), name='api_user_me'),
    path('api/user/<int:pk>/', api_views.UserRetrieveUpdateView.as_view(), name='api_user_detail_update'),
    path('api/user/<int:pk>/manage/', api_views.UserManageView.as_view(), name='api_user_manage'),
    path('api/user/register/', api_views.UserRegisterForAnyView.as_view(), name='api_user_register'),
    path('api/user/register-for-other/', api_views.UserRegisterForOtherView.as_view(), name='api_user_register_for_other'),
]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import PermissionsMixin, AbstractBaseUser, UserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _

def get_user_dir_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f"user_{instance.user.id}/{filename}"

# Create your models here.
class DepartmentManager(models.Manager):
    def create_department(self, alias, password, name, **kwargs):
        department = self.model(alias=alias, name=name, **kwargs)
        department.password = make_password(password)
        department.save(using=self._db)
        return department

class Department(models.Model):
    '''
    Biểu diễn các phòng trong cơ quan
    '''
    name = models.TextField()
    alias = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=150)
    objects = DepartmentManager()

    def __str__(self):
        return self.name

class Position(models.Model):
    '''
    Biểu diễn chức vụ trong tổ chức
    '''
    name = models.TextField()
    alias = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class User(AbstractBaseUser, PermissionsMixin):
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_('Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    date_joined = models.DateTimeField(default=timezone.now)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = UserManager()
    USERNAME_FIELD = 'username'

    # Thông tin chi tiết về User
    first_name = models.CharField(max_length=150)
    image = models.ImageField(default="default.jpg", upload_to=get_user_dir_path)
    address = models.TextField(blank=True)
    skill = models.TextField(blank=True)
    phone_number = models.TextField(blank=True)
    self_introduction = models.TextField(blank=True)
    email = models.EmailField(blank=True)
    layout_config = models.TextField(blank=True)

    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, blank=True)
    position = models.ForeignKey(Position, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return f"Tài khoản {self.username}"

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{h1header}}</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" type="text/css" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" type="text/css" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  
  <!-- Theme style -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/adminlte.min.css' %}">
  <style>
      .logo-software {
          width: 100%;
          display: flex;
          justify-content: center;
          align-items: center;
      }
      .center {
          width: 180px;
          display: block;
      }
      .my-page {
          min-height: 100vh !important;
          height: auto;
          flex-direction: column;
          justify-content: center;
      }
 </style>
</head>
<body class="hold-transition login-page my-page">

  <div class="logo-software">
    <img class='center' src="{% static 'img/logo-2.png' %}">
  </div>
  <div class="login-box">
   
    <div class="login-logo">
      <!-- <p>    <b>Công </b>Ty1</p> -->
      <p>     <b>Trang quản lý HSMT</b></p>
    </div>
    <!-- /.login-logo -->
    {% block body %}

    {% endblock %}
  </div>
  
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/jquery/jquery.validate.min.js' %}"></script>


<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.min.js' %}"></script>
  {% block script %}

  {% endblock %}
</body>

</html>

users/templates/users/group-list.html
{% extends "layout.html" %}
{% load static %}


{% block header %}{{ h1header }}{% endblock %}
{% block breadcrumb-text %}{{ breadcrumb }}{% endblock %}

{% block body %}
<section class="content">
  <div class="container-fluid">
    <div class="row py-2 px-2">
      <!-- <btn class="btn btn-success"  onclick="Edit();">Thêm bản ghi</btn> -->
      </div>
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Danh sách Nhóm người dùng</h3>
            <div class="card-tools">
              <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
                <div class="input-group-append">
                  <button type="submit" class="btn btn-default">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body table-responsive p-0" style="height: 100%;">
            <table class="table table-head-fixed text-nowrap table-striped">
              <thead>
                <tr>
                  <th style="width: 10%;">Số thứ tự</th>
                  <th>Nhóm ngườI dùng</th>
                  <th style="width: 10%;"></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>01</td>
                  <td><a href="#">Admin</a></td>
                  <td>
                    
                    
              </td>
                </tr>
                <tr>
                  <td>02</td>
                  <td><a href="#">Giám đốc</a></td>
                  <td>
                    
                    
              </td>
                </tr>
                <tr>
                  <td>03</td>
                  <td><a href="#">Trưởng Phòng</a></td>
                  <td>
                    
                    
              </td>
                </tr>
                <tr>
                    <td>04</td>
                    <td><a href="#">Người kiểm định</a></td>
                    <td>
                      
                      
                </td>
                  </tr>
                  <tr>
                    <td>05</td>
                    <td><a href="#">Trợ lý</a></td>
                    <td>
                      
                      
                 </td>
                  </tr>
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
    <!-- /.row -->

    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
<!-- Modal -->

{% endblock %}

{% block script %}
<!-- <script src="{% static 'js/custom.js' %}"></script> -->
<!-- <script>
  function Edit(){
    location.href = "#";
  };
</script> -->
{% endblock %}

users/templates/users/login.html
{% extends "users/base.html" %}

{% block body %}
<div class="card">
  <div class="card-body login-card-body">
    <p class="login-box-msg">Đăng nhập</p>
    {% if msg %}
    <p style="color: red;">Lỗi: {{msg}}</p>
    {% endif %}

    <form action="{% url 'user-login' %}" method="post">
      {% csrf_token %}
      <div class="input-group mb-3">
        <input type="text" class="form-control" placeholder="Tài khoản" name="username">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-envelope"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <input type="password" class="form-control" placeholder="Mật khẩu" name="password">
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-lock"></span>
          </div>
        </div>
      </div>


      <div class="row">
        <!-- /.col -->
        <div class="col-12">
          <button type="submit" class="btn btn-primary btn-block my-2">Đăng nhập</button>
        </div>
        <!-- /.col -->
      </div>
    </form>


    <!-- <p class="mb-1">
      <a href="forgot-password.html">Quên mật khẩu?</a>
    </p> -->
    <p class="mb-0">
      <a href="{% url 'user-register' %}" class="text-center">Đăng ký tài khoản</a>
    </p>
  </div>
  <!-- /.login-card-body -->
</div>
{% endblock %}

users/templates/users/profile.html
{% extends "layout.html" %}
{% load static %}


{% block header %}{{ h1header }}{% endblock %}
{% block breadcrumb-text %}{{ breadcrumb }}{% endblock %}

{% block body %}
<section class="content">
  <div class="container-fluid">
    <div class="row">
        <div class="col-md-3">

          <!-- Profile Image -->
          <div class="card card-primary card-outline">
            <div class="card-body box-profile">
              <div class="text-center">
                <img class="profile-user-img img-fluid img-circle" src="{% static 'img/avatar5.png' %}" alt="User profile picture">
              </div>

              <h3 class="profile-username text-center">{{user.first_name}}</h3>

              <p class="text-muted text-center">({{user.username}})</p>

              <ul class="list-group list-group-unbordered mb-3">
                <li class="list-group-item">
                    <b>Chức vụ</b> <span class="float-right">{{user.group_name}}</span>
                </li>
                <li class="list-group-item">
                  <b>HSMT</b> <span class="float-right">{{user.totalXfile}}</span>
                </li>
                

              </ul>
              {% if user.is_active == 1 %}
              <btn type="button" class="btn btn-success btn-block"><b>Đã kích hoạt</b></btn>

              {% else %}
              <btn type="button" class="btn btn-danger btn-block"><b>Chưa kích hoạt</b></btn>

              {% endif %}


            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->


        </div>
        <!-- /.col -->
        <div class="col-md-9">
          <div class="card">
            <div class="card-header p-2">
              <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link active" href="#user-info" data-toggle="tab">Thông tin cá nhân</a></li>
                {% if selfProfile %}
                <li class="nav-item"><a class="nav-link" href="#profile-notification" data-toggle="tab" id="profile-notification-tab">Thông báo của tôi</a></li>
                <li class="nav-item"><a class="nav-link" href="#information" data-toggle="tab">Cập nhật thông tin</a></li>
                <li class="nav-item"><a class="nav-link" href="#setting" data-toggle="tab">Mật khẩu</a></li>
                {% endif %}

              </ul>
            </div><!-- /.card-header -->
            <div class="card-body">
              <div class="tab-content">
                <div class="tab-pane active" id="user-info">
                          <!-- About Me Box -->
                    <strong><i class="far fa-file-alt mr-1"></i> Tự giới thiệu</strong>

                    {% if userInfo.self_introduction == "" %} <p class="text-muted">Không có dữ liệu</p> {% else %}<p class="text-muted">  {{userInfo.self_introduction}} {% endif %}</p> 

                    <hr>

                    <strong><i class="fas fa-map-marker-alt mr-1"></i> Địa chỉ</strong>

                        {% if userInfo.address == "" %} <p class="text-muted">Không có dữ liệu</p> {% else %} <p class="text-muted"> {{userInfo.address}} {% endif %}</p> 

                    <hr>

                    <strong><i class="fas fa-pencil-alt mr-1"></i> Kĩ năng</strong>

                    
                        {% if userInfo.skill == "" %} <p class="text-muted">Không có dữ liệu</p> {% else %}<p class="text-muted"> {{userInfo.skill}} {% endif %}</p> 
                    

                    <hr>

                    <strong><i class="fas fa-phone-square-alt mr-1"></i> Số điên thại</strong>

                    {% if userInfo.phone_number == "" %} <p class="text-muted">Không có dữ liệu</p> {% else %} <p class="text-muted"> {{userInfo.phone_number}} {% endif %}</p> 
          <!-- /.card -->
                </div>
                <!-- /.tab-pane -->
                {% if selfProfile %}
                <div class="tab-pane" id="profile-notification">

                </div>
                <div class="tab-pane" id="information">
                    <form class="form-horizontal" action="{% url 'edit-user-info' %}" method="post">{% csrf_token %}    
 
                    <div class="form-group row">
                      <label for="first_name" class="col-sm-2 col-form-label">Họ tên</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="first_name" placeholder="Họ tên" value="{{user.first_name}}">
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="phoneNumber" class="col-sm-2 col-form-label">Số điện thoại</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="phone_number" placeholder="..." value="{{userInfo.phone_number}}">
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="address" class="col-sm-2 col-form-label">Địa chỉ</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="address" placeholder="Địa chỉ" value="{{userInfo.address}}">
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="selfIntro" class="col-sm-2 col-form-label">Tự giới thiệu</label>
                      <div class="col-sm-10">
                        <textarea class="form-control" name="self_introduction" placeholder="Về bản thân.." >{{userInfo.self_introduction}}</textarea>
                      </div>
                    </div>
                    <div class="form-group row">
                      <label for="inputSkills" class="col-sm-2 col-form-label">Skills</label>
                      <div class="col-sm-10">
                        <input type="text" class="form-control" name="skill" placeholder="Kĩ năng" value="{{userInfo.skill}}">
                      </div>
                    </div>

                    <div class="form-group row">
                      <div class="offset-sm-2 col-sm-10">
                        <button type="submit" class="btn btn-success" id="btnSaveUserInfo">Lưu</button>
                      </div>
                    </div>
                  </form>
                </div>
                <div class="tab-pane" id="setting">
                    <form class="form-horizontal">
                      <div class="form-group row">
                        <label for="oldPassword" class="col-sm-2 col-form-label">Mật khẩu cũ</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="oldPassword" placeholder="Mật khẩu cũ của bạn">
                        </div>
                      </div>
                    <div class="form-group row">
                        <label for="newPassword" class="col-sm-2 col-form-label">Mật khẩu mới</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="newPassword" placeholder="Mật khẩu mới">
                        </div>
                      </div>
                    <div class="form-group row">
                      <label for="reNewPassowrd" class="col-sm-2 col-form-label">Nhập lại Mật khẩu mới</label>
                      <div class="col-sm-10">
                        <input type="password" class="form-control" id="reNewPassowrd" placeholder="Nhập lại Mật khẩu mới">
                      </div>
                    </div>


                    <div class="form-group row">
                      <div class="offset-sm-2 col-sm-10">
                        <button type="button" class="btn btn-danger" id="btnChangePassword">Đổi mật khẩu</button>
                      </div>
                    </div>
                  </form>
                </div>
                {% endif %}

                <!-- /.tab-pane -->
              </div>
              <!-- /.tab-content -->
            </div><!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
    <!-- /.row -->
  </div><!-- /.container-fluid -->
</section>
{% endblock %}

{% block script %}
<script >
 $('#btnSaveUserInfo').on('click',function(){
    showNotification('Gửi yêu cầu thành công');
 });

</script>
<script src="{% static 'js/profile.js' %}"></script>

{% endblock %}

users/templates/users/register.html
{% extends "users/base.html" %}

{% load static %}


{% block body %}

<div class="card" >
    <div class="card-body register-card-body">
      <p class="login-box-msg">Đăng ký tài khoản</p>
      {% if msg %}
      <p style="color: red;">Lỗi: {{msg}}</p>
      {% endif %}
      <form class="needs-validation" action="" id="formDangKi"  method="post" name="formDangKi" novalidate >{% csrf_token %}
        <div class="form-group">
          Username<input type="text" id = "username" name = "username" class="form-control" required autofocus>
          <div class="valid-feedback">Hợp lệ</div>
          <div class="invalid-feedback">Nhập vào tài khoản</div>
        </div>
        <div class="form-group">
          Password<input type="password" id="password" name = "password" class="form-control pwds" pattern="^[a-zA-Z0-9]{8,100}$" required>
          <div class="valid-feedback">Hợp lệ</div>
          <div class="invalid-feedback">Ít nhất 8 kí tự</div>
        </div>
        <div class="form-group">
          Confirm Password<input type="password" id="password2" name = "password2" class="form-control pwds" pattern="^[a-zA-Z0-9]{8,100}$" required>
          <div id="cPwdValid" class="valid-feedback">Hợp lệ</div>
          <div id="cPwdInvalid" class="invalid-feedback"> Ít nhất 8 kí tự</div>
        </div>
      
        <div class="form-group">
          Họ và tên<input type="text" id = "fullname" name = "fullname" class="form-control" pattern="^(?!\s*$).+" required autofocus>
          <div class="valid-feedback">Hợp lệ</div>
          <div class="invalid-feedback">Nhập họ tên đầy đủ</div>
        </div>
        
        <div class="input-group mb-3">
          <select class="custom-select" id="inputGroupSelect01" id="phong" name="phong" required>
              <option class="py-3" value="">Chọn Phòng...</option>
              {% for department in department_list %}
                <option class="py-3" value="{{department.id}}">{{department.name}}</option>
              {% endfor %}

            </select>
            <div class="valid-feedback">Hợp lệ</div>
            <div class="invalid-feedback">Chọn phòng</div>
  
        </div>



        <div class="form-group">
          <button id="submitBtn" type="submit" class="btn btn-primary submit-button" disabled>Submit</button>
        </div>






      </form>

      <!-- <div class="social-auth-links text-center">
        <p>- OR -</p>
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i>
          Sign up using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i>
          Sign up using Google+
        </a>
      </div> -->










      <a href="{% url 'user-login' %}" class="text-center">Tôi đã có tài khoản</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->

  {% endblock %}

 
  {% block script %}
  <script src="{% static 'js/register.js' %}"></script>
  

  <script >
     
 

  </script>


  {% endblock %}

users/templates/users/success.html
{% extends "users/base.html" %}
{% block body %}

<div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg text-success">Tài khoản đã được tạo</p>
      <p class="login-box-msg">Hãy liên hệ với trưởng phòng <b>Phòng {{departmentNumber}}</b> để kích hoạt tài khoản</p>
      <p class="login-box-msg"><a href="/" class="btn btn-primary mt-2">Quay lại</a>
      </p>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
  {% endblock %}

  